### ISSUE TITLE
[Feature request] Tab name should reflect the file name after "Save As..."

### ISSUE THREAD

**Issue by jjbaron** [francisfeng/everything-okjson#13]
**Is your feature request related to a problem? Please describe.**
When I "Save As..." the json for the tab in focus, the tab name does not change.

**Describe the solution you'd like**
I would like the tab name to reflect the name of the file I just saved.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by francisfeng** [comment]
Implemented.
