### ISSUE TITLE
while editing subsection view of json doc, cursor always moves to the end of doc

### ISSUE THREAD

**Issue by joshorr** [francisfeng/everything-okjson#15]
**Describe the bug**

While editing subsection view of json doc, cursor always moves to the end of doc.

**To Reproduce**

Create doc/window with json that has sub-objects/dict, ie:

```
{
    "a": {
        "s": {
            "hello": 2
        }
    }
}
```

On the left side (in the above JSON example) click the `> { } s` part.

Then on the right start editing the "hello" part of the subview (ie: only a part of the json is visible due to clicking the `> { } s` part.

The cursor jumps to bottom of document after every time you type a single character.

**Expected behavior**
Cursor stays where it is at so you can continue typing.

**Screenshots**

Place cursor in middle of `"hello"`:

<img width="925" alt="Screenshot 2023-02-23 at 8 50 50 PM" src="https://user-images.githubusercontent.com/1890452/221087592-55e11abb-81ed-4d1d-a23e-ad8eb22b9f9e.png">

I typed a capital `T` and cursor the moved to bottom of document:

<img width="924" alt="Screenshot 2023-02-23 at 8 49 58 PM" src="https://user-images.githubusercontent.com/1890452/221087635-cc2fcc02-e471-4da6-a62c-47ca9b1194da.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Browser Safari
 - Version 1.9.0 (25)

**Comment by francisfeng** [comment]
It’s a known issue.

I’m planing a new version in which the edition on the right pane will no longer automatically being reflected on the left pane. It should solve the many problems, this one included, resulting from the syncing between both panes.

**Comment by joshorr** [comment]
I actually like that feature, it's kind of sad your removing it.
