### ISSUE TITLE
Tab names are broken when adding a new tab in the middle of existing tabs

### ISSUE THREAD

**Issue by shames0** [francisfeng/everything-okjson#17]
**Describe the bug**
When you have two or more tabs open and each is named, creating a new tab while focused on any but the last tab causes the new tab to take on an existing tab's name.

**To Reproduce**
1. From a new OK JSON window, paste JSON content, or open a JSON file to populate the window
2. Use the "Rename tab" button to name the current window (e.g. "Test Tab 1")
3. Use cmd + t to open a new tab, and populate this window with JSON that is distinct from the first window
4. Use the "Rename tab" button to name this second window (e.g. "Test Tab 2")
5. Switch to the first window ("Test Tab 1")
6. Press cmd + to to create a new tab
7. Notice that the new tab's title is now "Test Tab 2", and the content you had in "Test Tab 2" before is now in a tab named "Today at {TIME}"

**Expected behavior**
Would expect the tab names to stick with the content that was placed in them, rather than changing content when the new tab is created.

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1 (22D68)
 - Browser: N/A - using the macOS "OK JSON" app
 - Version: Version 1.9.0 (26)

**Comment by francisfeng** [comment]
Fixed in 1.9.1.
