### ISSUE TITLE
Save function not working property

### ISSUE THREAD

**Issue by Kyle-Ye** [francisfeng/everything-okjson#3]
**Describe the bug**
Click the "save as" menu did nothing.

**To Reproduce**
1. Get a JSON string, and open it in "OK JSON.app"
2. Choose the top JSON object and click on "Save as" menu or press  ⇧ ⌘ S
3. See bug(Nothing happends)

**Expected behavior**
Present a windows query where to save the json file

**Screenshots**
<img width="405" alt="截屏2021-09-09 17 15 02" src="https://user-images.githubusercontent.com/43724855/132658511-2d81a3de-f207-491d-bf21-d1cb98d85f55.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.0 beta5 21A5506j
 - App Version: version 1.3 (8)

**Additional context**
No

**Comment by francisfeng** [comment]
Thanks for the report.

Issue identified. Will be fixed in next version.
