### ISSUE TITLE
[Feature request] Menu String Suggestion

### ISSUE THREAD

**Issue by Kyle-Ye** [francisfeng/everything-okjson#4]
**Is your feature request related to a problem? Please describe.**
I always feel a little strange when I see "JSONPath" and "JSON Patch" appear in the same place 😂
<img width="274" alt="截屏2021-09-10 10 59 26" src="https://user-images.githubusercontent.com/43724855/132793208-38e17796-dbe9-4d98-86e2-da2db9ad176e.png">

**Describe the solution you'd like**
Change "JSONPath" into "JSON Path" to unify the string format

**Describe alternatives you've considered**
Change "JSON Patch" into "JSONPatch" (Personal I prefer the former)

**Additional context**
I know JSONPath is the Library's Name. But I think that's how it is used in an API (no space in between, Camel-Case Rule).
When we use it in another context, maybe a space is more proper. ♥️

**Comment by francisfeng** [comment]
Like XPath, JSONPath is a query language for selecting nodes from an JSON document. It's not just the library's name. It's the name.

So I think OK JSON should stick to the nomenclature.
