### ISSUE TITLE
[Bug report] 行号显示异常

### ISSUE THREAD

**Issue by Kyle-Ye** [francisfeng/everything-okjson#5]
**Describe the bug**
在数据过多时，行号显示异常

**To Reproduce**
1. 复制附件的JSON数据，或者自行找到一条200行+的JSON数据
2. 使用OKJSON打开
3. 下滑到100行左右
4. 发现部分行号被隐藏
> 注：可通过移动行号左侧的分割线，来使得UI刷新临时解决局部行号显示，但继续上滑或下滑问题仍然存在

**Expected behavior**
行数全部显示或者按其他可预期的规则显示部分

**Screenshots**
<img width="1920" alt="截屏2021-09-10 15 53 53" src="https://user-images.githubusercontent.com/43724855/132819947-9d822e4c-b23e-4ae4-9a4c-2c505c6852d7.png">

**Desktop (please complete the following information):**

OS: macOS 12.0 beta5 21A5506j
App Version: version 1.3 (8)

**Additional context**
附件📎👇
[test.txt](https://github.com/francisfeng/everything-okjson/files/7142166/test.txt)

**Comment by francisfeng** [comment]
这个应该是 macOS 12.0 的问题，macOS Big Sur 下显示数万行的 JSON 也未发现此问题。

我还没有安装新系统，我尽量在新系统正式发布前安装 Beta 版，届时才能尝试解决。

**Comment by francisfeng** [comment]
新版本内已修复此问题，等待上线。
