### ISSUE TITLE
Change tab name 

### ISSUE THREAD

**Issue by tierracero** [francisfeng/everything-okjson#8]
**Is your feature request related to a problem? Please describe.**
I have up to 10 tabs  open and  need  look to each to know witch one it is

**Describe the solution you'd like**
be able to a double clic on the  tab to change name

 thanks in advance  I love your app

**Comment by francisfeng** [comment]
It's actually changeable in current version.

Select the root node -> Press Return key to rename -> The new value will be used as the window title (tab name).

I will add more visual way to change window title since it's the most asked question.
